name: Deploy to Nginx Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to Nginx server
      run: |
        scp -P 2222 -r -o StrictHostKeyChecking=no ./* vagrant@localhost:/var/www/html

    - name: Restart Nginx
      run: |
        ssh -p 2222 -o StrictHostKeyChecking=no vagrant@localhost << 'EOF'
        sudo systemctl restart nginx
        EOF
